version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: ddos-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ddos
    environment:
      - MYSQL_DATABASE=ddos
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
    restart: unless-stopped

  backend:
    build: ./app
    container_name: ddos-app
    ports:
      - 7000:8000
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - DB_PASSWORD="${MYSQL_PASSWORD:-}"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - ddos

networks:
  ddos:
    driver: bridge

volumes:
  mysql-data: {}